include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
    sort_child_properties_last: false
    depend_on_referenced_packages: false
    prefer_interpolation_to_compose_strings: false
    require_trailing_commas: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
